# .gitea/workflows/build-preview.yaml
name: Build Preview Container
on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set PR Name as Tag
        run: |
          echo "PR_TAG=preview-${{ github.event.number }}" >> $GITHUB_ENV
      
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: gitea.local:3000/gitea_admin/sample-application:${{ env.PR_TAG }}