---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-application
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sample-application
  template:
    metadata:
      labels:
        app: sample-application
    spec:
      containers:
      - name: sample-application
        image: gitea.local:3000/gitea_admin/sample-application:latest  # Kustomize will replace this tag
        ports:
        - containerPort: 8080
